name: DEPLOY TO STAGING
on:
    pull_request:
        types: [closed]
        branches:
            - dev

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: dev
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - run: npm install
            - run: npm run bundle
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'deploy/'
                  REMOTE_HOST: 'ec2-18-117-253-229.us-east-2.compute.amazonaws.com' 
                  REMOTE_USER: ubuntu
                  TARGET: 'nodeapps/survey-backend'
            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              env:
                  NAME: 'root'
              with:
                  hosts: 'ubuntu@ec2-18-117-253-229.us-east-2.compute.amazonaws.com'
                  privateKey: ${{ secrets.SERVER_SSH_KEY }}
                  debug: false
                  command: |
                      cd nodeapps/survey-backend
                      npm install
                      sudo mkdir app
                      sudo mv config controllers middleware models routes app
                      sudo rm -rf config controllers middleware models routes
                      sudo systemctl stop survey-backend
                      sudo cp survey-backend.service /lib/systemd/system/survey-backend.service
                      sudo rm survey-backend.service
                      sudo systemctl daemon-reload
                      sudo systemctl start survey-backend


